const { Router } = require('express');
const healthRoutes = require('./health.routes');
const authRoutes = require('./auth.routes');
const uploadRoutes = require('./upload.routes');
const adminRoutes = require('./admin.routes');
const movieRoutes = require('./movie.routes');
const movieSectionRoutes = require('./movieSection.routes');
const musicRoutes = require('./music.routes');
const musicSectionRoutes = require('./musicSection.routes');
const albumRoutes = require('./album.routes');
const clipRoutes = require('./clip.routes');
const clipSectionRoutes = require('./clipSection.routes');
const concertRoutes = require('./concert.routes');
const concertSectionRoutes = require('./concertSection.routes');
const actorRoutes = require('./actor.routes');
const actorPageLabelRoutes = require('./actorPageLabel.routes');
const bannerRoutes = require('./banner.routes');
const genreRoutes = require('./genre.routes');
const categoryRoutes = require('./category.routes');
const adRoutes = require('./ad.routes');
const shortVideoRoutes = require('./shortVideo.routes');
const siteLinksRoutes = require('./siteLinks.routes');
const videoBannerRoutes = require('./videoBanner.routes');
const artistMusicStoryRoutes = require('./artistMusicStory.routes');
const artistRoutes = require('./artist.routes');
const musicShortRoutes = require('./musicShort.routes');
const musicBannerRoutes = require('./musicBanner.routes');
const trillerRoutes = require('./triller.routes');

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/uploads', uploadRoutes);
router.use('/admin', adminRoutes);
router.use('/movies', movieRoutes);
router.use('/actors', actorRoutes);
router.use('/actor-page-labels', actorPageLabelRoutes);
router.use('/banners', bannerRoutes);
router.use('/genres', genreRoutes);
router.use('/categories', categoryRoutes);
router.use('/ads', adRoutes);
router.use('/shorts', shortVideoRoutes);
router.use('/site-links', siteLinksRoutes);
router.use('/video-banners', videoBannerRoutes);
router.use('/movie-sections', movieSectionRoutes);
router.use('/music', musicRoutes);
router.use('/music-sections', musicSectionRoutes);
router.use('/albums', albumRoutes);
router.use('/clips', clipRoutes);
router.use('/clip-sections', clipSectionRoutes);
router.use('/concerts', concertRoutes);
router.use('/concert-sections', concertSectionRoutes);
router.use('/artist-music-stories', artistMusicStoryRoutes);
router.use('/artists', artistRoutes);
router.use('/music-shorts', musicShortRoutes);
router.use('/music-banners', musicBannerRoutes);
router.use('/trillers', trillerRoutes);

module.exports = router;
