/**
 * Hit Collections (Mashhur to'plamlar) - Albom bo'limi uchun ma'lumotlar.
 * Kartochka bosilsa MusicAlbumDetail sahifasiga chiqadi.
 */
export const hitCollectionsData = [
  {
    id: 1001,
    title: "Best of 2025",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Pop',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Hit One", artist: "Jonny", audio: "/music/Zivert - Life.mp3" },
      { id: 2, title: "Hit Two", artist: "Artist B", audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3" },
    ],
  },
  {
    id: 1002,
    title: "Summer Hits",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Pop',
    language: 'english',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Sun", artist: "Jonny", audio: "/music/Reed Wonder - When I Dream Of You.mp3" },
      { id: 2, title: "Beach", artist: "Artist B", audio: "/music/Zivert - Life.mp3" },
    ],
  },
  {
    id: 1003,
    title: "Night Vibes",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-2.jpeg",
    year: 2024,
    genre: 'Rap',
    language: 'english',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Midnight", artist: "Jonny", audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3" },
    ],
  },
  {
    id: 1004,
    title: "Top Mix",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2023,
    genre: 'Pop',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Mix", artist: "Artist B", audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3" },
      { id: 2, title: "Top", artist: "Jonny", audio: "/music/Zivert - Life.mp3" },
    ],
  },
  {
    id: 1005,
    title: "Golden Era",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2023,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Golden", artist: "Jonny", audio: "/music/Reed Wonder - When I Dream Of You.mp3" },
    ],
  },
  {
    id: 1006,
    title: "Urban Sound",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-3.jpg",
    year: 2024,
    genre: 'Pop',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Urban", artist: "Artist B", audio: "/music/Zivert - Life.mp3" },
      { id: 2, title: "Sound", artist: "Jonny", audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3" },
    ],
  },
  {
    id: 1007,
    title: "Chart Toppers",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/jah-khalib.jpg",
    year: 2025,
    genre: 'Pop',
    language: 'english',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Chart", artist: "Jonny", audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3" },
    ],
  },
  {
    id: 1008,
    title: "Electric Pulse",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie1.jpg",
    year: 2024,
    genre: 'electronic',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Electric", artist: "Artist B", audio: "/music/Reed Wonder - When I Dream Of You.mp3" },
      { id: 2, title: "Pulse", artist: "Jonny", audio: "/music/Zivert - Life.mp3" },
    ],
  },
  {
    id: 1009,
    title: "Rhythm Collection",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie2.jpg",
    year: 2023,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Rhythm", artist: "Jonny", audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3" },
    ],
  },
  {
    id: 1010,
    title: "Ultimate Hits",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2025,
    genre: 'Pop',
    language: 'english',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Ultimate", artist: "Artist B", audio: "/music/Zivert - Life.mp3" },
      { id: 2, title: "Hits", artist: "Jonny", audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3" },
    ],
  },
  {
    id: 1011,
    title: "Star Collection",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie5.jpg",
    year: 2024,
    genre: 'Pop',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      { id: 1, title: "Star", artist: "Jonny", audio: "/music/Reed Wonder - When I Dream Of You.mp3" },
      { id: 2, title: "Collection", artist: "Artist B", audio: "/music/Zivert - Life.mp3" },
    ],
  },
];
