/**
 * Live Stages (Jonli sahnalar) - konsert video bo'limi uchun ma'lumotlar.
 * type: 'konsert' - jonli konsert video kontent.
 */
export const liveStagesData = [
  {
    id: 1501,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Die With A Smile',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '1110',
    dislike: '0',
  },
  {
    id: 1502,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Live Performance',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1503,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Life',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1504,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-4.webp',
    title: 'Concert Highlights',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1505,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-5.jpg',
    title: 'Live At Stadium',
    year: 2024,
    genre: 'thriller',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1506,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Premiere Live',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1507,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-7.jpg',
    title: 'Official Live',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1508,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-8.jpg',
    title: 'Concert Special',
    year: 2024,
    genre: 'drama',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1509,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-9.jpg',
    title: 'Zivert Live',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1510,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-10.jpg',
    title: 'Music Video Live',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
];
