/**
 * Music Hub - Musiqa markazi bo'limi uchun ma'lumotlar.
 * type: 'music' - audio trek.
 */
export const musicHubData = [
  {
    id: 701,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Violet Dreams',
    year: 2025,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Binafsha tushlar - menga yo'ldosh\nViolet dreams - abadiy\nHar kecha sen bilan",
  },
  {
    id: 702,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'City Soul',
    year: 2024,
    genre: 'Rap',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Shahar ruhi - har bir ko'chada\nCity soul - sen bilan\nBu dunyo - bizniki",
  },
  {
    id: 703,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Midnight Groove',
    year: 2023,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Yarim tun ritmi - yulduzlar ostida\nMidnight groove - raqsga tush\nAbadiy kecha",
  },
  {
    id: 704,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: 'Sunset Boulevard',
    year: 2024,
    genre: 'hip-hop',
    language: 'russian',
    country: 'russia',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Quyosh botish bulvari\nHar bir kun - yangi\nSunset boulevard - hayot",
  },
  {
    id: 705,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Echo Valley',
    year: 2022,
    genre: 'electronic',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Echo valley - ovozing\nHar bir echo - xotira\nValley - abadiy",
  },
  {
    id: 706,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Neon Lights',
    year: 2025,
    genre: 'pop',
    language: 'korean',
    country: 'korea',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Neon chiroqlari - kechasi\nShahar yoniq - sensiz emas\nNeon lights - bizniki",
  },
  {
    id: 707,
    artistId: 'michael-jackson',
    img: '/img/movie1.jpg',
    title: 'Smooth Operator',
    year: 2023,
    genre: 'jazz',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Smooth operator - sen\nHar bir harakat - san'at\nOperator - hayot",
  },
  {
    id: 708,
    artistId: 'shohruhxon',
    img: '/img/movie2.jpg',
    title: 'River Flow',
    year: 2024,
    genre: 'pop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Daryo oqimi - abadiy\nRiver flow - sensiz emas\nHar tomchi - xotira",
  },
  {
    id: 709,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Sky High',
    year: 2022,
    genre: 'Rock',
    language: 'english',
    country: 'kanada',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Osmon baland - sen bilan\nSky high - muhabbat\nAbadiy parvoz",
  },
  {
    id: 710,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Thunder Storm',
    year: 2025,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Momaqaldiroq bo'roni - kuchli\nThunder storm - sensiz emas\nHar bir chaqmoq - senga",
  },
  {
    id: 711,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Desert Wind',
    year: 2023,
    genre: 'pop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Cho'l shamoli - issiq\nDesert wind - menga yo'ldosh\nSahro - bizniki",
  },
];
