/**
 * Sevgi va Musiqa (Love and Music) - Albom bo'limi uchun ma'lumotlar.
 * Kartochka bosilsa MusicAlbumDetail sahifasiga chiqadi.
 */
export const sevgiVaMusiqaData = [
  {
    id: 901,
    title: "Love Stories",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Pop',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "First Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Forever Yours",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 3,
        title: "Heartbeat",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 902,
    title: "Romantic Nights",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Pop',
    language: 'english',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Moonlight",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Stargazing",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
    ],
  },
  {
    id: 903,
    title: "Soul Connection",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-2.jpeg",
    year: 2023,
    genre: 'Rap',
    language: 'english',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Soul",
        artist: "Jonny",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 2,
        title: "Connection",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 904,
    title: "Sweet Melodies",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2024,
    genre: 'Pop',
    language: 'english',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Sweet",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 905,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 906,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 907,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 908,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 909,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 910,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 911,
    title: "Eternal Love",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2022,
    genre: 'Jazz',
    language: 'english',
    country: 'USA',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Eternal",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Love",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
];
