/**
 * Stars Stage (Yulduzlar sahasi) - konsert video bo'limi uchun ma'lumotlar.
 * type: 'konsert' - yulduzlar sahna konsert video kontent.
 */
export const starsStageData = [
  {
    id: 1601,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Die With A Smile',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '110',
    dislike: '0',
  },
  {
    id: 1602,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Stars Stage Performance',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1603,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Life on Stage',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1604,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-4.webp',
    title: 'Stars Concert',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1605,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-5.jpg',
    title: 'Stars Stage Special',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1606,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Premiere Stars',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1607,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-7.jpg',
    title: 'Official Stars Stage',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1608,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-8.jpg',
    title: 'Concert Stars',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1609,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-9.jpg',
    title: 'Stars Live',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'konsert',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1610,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-10.jpg',
    title: 'Stars Stage Live',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'konsert',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
];
