/**
 * Top Nasheeds - Top Nashidalar bo'limi uchun ma'lumotlar.
 * type: 'music' - islamiy ilohiy qo'shiqlar.
 */
export const topNasheedsData = [
  {
    id: 901,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg1.jpg',
    title: 'Bismillah',
    year: 2024,
    genre: 'nasheed',
    language: 'arabic',
    country: 'saudi',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Bismillah ar-Rahman ar-Rahim\nHar bir ishni Uning nomi bilan boshlaymiz",
  },
  {
    id: 902,
    artistId: 'sami-yusuf',
    img: '/img/nasheedsimg2.jpg',
    title: 'Al-Quran Al-Kareem',
    year: 2023,
    genre: 'nasheed',
    language: 'arabic',
    country: 'saudi',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: `Al-Quran Al-Kareem - ilohiy so'z\nUmmat uchun rahmat`,
  },
  {
    id: 903,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg3.jpg',
    title: 'نشيد',
    year: 2024,
    genre: 'nasheed',
    language: 'arabic',
    country: 'egypt',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: `Nasheed - ilohiy qo'shiq\nYuragimni tinchlantiradi`,
  },
  {
    id: 904,
    artistId: 'sami-yusuf',
    img: '/img/nasheedsimg4.jpg',
    title: 'Oydin tun',
    year: 2023,
    genre: 'nasheed',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Oydin tun - masjid oldida\nDua va ilohiy ohang",
  },
  {
    id: 905,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg5.jpg',
    title: "Cho'l va oy",
    year: 2022,
    genre: 'nasheed',
    language: 'arabic',
    country: 'uae',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: `Cho'l va oy - tinchlik\nIlohiy muhabbat`,
  },
  {
    id: 906,
    artistId: 'sami-yusuf',
    img: '/img/nasheedsimg6.jpg',
    title: 'Masjid va fonus',
    year: 2025,
    genre: 'nasheed',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Masjid va fonus - ramazon\nIlohiy nur",
  },
  {
    id: 907,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg7.jpg',
    title: 'Eid Mubarak',
    year: 2024,
    genre: 'nasheed',
    language: 'arabic',
    country: 'saudi',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Eid Mubarak - bayram kutibi\nUmmat bilan birga",
  },
  {
    id: 908,
    artistId: 'sami-yusuf',
    img: '/img/nasheedsimg8.jpg',
    title: "Qur'on va suv",
    year: 2023,
    genre: 'nasheed',
    language: 'arabic',
    country: 'egypt',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Qur'on va suv - tinchlik\nIlohiy soz aks etadi",
  },
  {
    id: 909,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg9.jpg',
    title: 'Dua qollari',
    year: 2024,
    genre: 'nasheed',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Dua qollari - iltijo\nAllohga yuzlanamiz",
  },
  {
    id: 910,
    artistId: 'sami-yusuf',
    img: '/img/nasheedsimg10.jpg',
    title: 'Bismillah va masjid',
    year: 2023,
    genre: 'nasheed',
    language: 'arabic',
    country: 'saudi',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Bismillah - har bir ishda\nMasjid - Alloh uyi",
  },
  {
    id: 911,
    artistId: 'maher-zain',
    img: '/img/nasheedsimg11.jpg',
    title: 'Ummat birdamligi',
    year: 2025,
    genre: 'nasheed',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Ummat birdamligi - kuch\nDua va muhabbat",
  },
];
