export const trendMusicData = [
  {
    id: 101,
    artistId: 'jah-khalib',
    img: '/img/TheWeeknd_Banner_Mobile.webp',
    title: "Life",
    year: 2020,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Leyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman.\n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman \n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman.\n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman",
  },
  {
    id: 103,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: "Wrong",
    year: 2012,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Sevgi – bu nima? Bilmayman hali\nFaqat sensiz yashab ko'rdim\nSevgi – bu sening ko'zlaring\nSevgi – bu sening so'zlaring\n\nQachon tushunsam, sevsam seni\nDunyoning eng baxtlisi bo'laman\nSevgi – bu menga yangi his\nSevgi – bu senga berilgan hayot",
  },
  {
    id: 104,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Sariq devona",
    year: 2022,
    genre: 'hip-hop',
    language: 'english',
    country: 'kanada',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Sariq devona, sen kim eding?\nMeni qayerlarga olib ketding\nSariq devona, tushunmadim\nNima uchun sensiz qoldim\n\nQaytib kel, sariq devona\nYana bir bor ko'rayin seni\nSariq devona, menga kerak sensan\nOlamni birga kezaylik",
  },
  {
    id: 105,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-2.jpeg',
    title: "Monkeys",
    year: 2015,
    genre: 'Rock',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Sariq devona, sen kim eding?\nMeni qayerlarga olib ketding\nSariq devona, tushunmadim\nNima uchun sensiz qoldim\n\nQaytib kel, sariq devona\nYana bir bor ko'rayin seni\nSariq devona, menga kerak sensan\nOlamni birga kezaylik",
  },
  {
    id: 106,
    artistId: 'jah-khalib',
    img: '/img/movie5.jpg',
    title: "Red wonder",
    year: 2023,
    genre: 'Electronic',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "",
  },
  {
    id: 107,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Under loves",
    year: 2017,
    genre: 'hip-hop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 108,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2026,
    genre: 'opera',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 109,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2010,
    genre: 'jazz',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1010,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2020,
    genre: 'Rap',
    language: 'Turish',
    country: 'Turkey',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1011,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2023,
    genre: 'Rock',
    language: 'Turkish',
    country: 'Turkey',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1012,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2024,
    genre: 'Electronic',
    language: 'japanese',
    country: 'japan',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1013,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2020,
    genre: 'pop',
    language: 'korean',
    country: 'korea',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1014,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2012,
    genre: 'Rap',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1015,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2020,
    genre: 'pop',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1016,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2017,
    genre: 'hip-hop',
    language: 'qozoqcha',
    country: 'qozogiston',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1017,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2019,
    genre: 'pop',
    language: 'qozoqcha',
    country: 'qozogiston',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
  {
    id: 1018,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: "Face love",
    year: 2018,
    genre: 'Rock',
    language: 'qozoqcha',
    country: 'qozogiston',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
  },
];
