/**
 * Musiqa / klip / konsert uchun umumiy country + genre facet ma'lumotlari.
 * Domain fayllar faqat NOISE_WORDS va parse/match funksiyalarini ushlab turadi.
 */

const MEDIA_COUNTRY_FACETS = [
  {
    values: ['usa', 'USA'],
    aliases: [
      'usa',
      'amerika',
      'america',
      'aqsh',
      'shtat',
      'united states',
      'америка',
      'американский',
      'американские',
      'сша',
    ],
  },
  {
    values: ['uzbekistan', 'Uzbekistan', 'Uzbekiston'],
    aliases: [
      'uzbekistan',
      'uzbekiston',
      'uzbek',
      'ozbek',
      'o zbek',
      "o'zbek",
      'ozbekcha',
      "o'zbekcha",
      'uzbekcha',
      'ozb',
      'uzb',
      'узбекистан',
      'узбекский',
      'узбекские',
      'узбекское',
    ],
  },
  {
    values: ['russia', 'Russia'],
    aliases: [
      'russia',
      'rossiya',
      'rassiya',
      'rassia',
      'rus',
      'ruscha',
      'россия',
      'русский',
      'русские',
      'русское',
      'российский',
      'российские',
    ],
  },
  {
    values: ['britaniya', 'uk', 'UK'],
    aliases: [
      'britaniya',
      'uk',
      'ingliz',
      'angliya',
      'britain',
      'england',
      'buyuk britaniya',
      'британия',
      'англия',
      'английский',
      'английские',
      'британский',
      'британские',
    ],
  },
  {
    values: ['kanada', 'canada', 'Canada'],
    aliases: [
      'kanada',
      'canada',
      'kanadacha',
      'канада',
      'канадский',
      'канадские',
    ],
  },
  {
    values: ['korea', 'Korea'],
    aliases: [
      'korea',
      'koreya',
      'korean',
      'koreys',
      'koreyscha',
      'karischa',
      'karea',
      'корея',
      'корейский',
      'корейские',
      'корейское',
    ],
  },
  {
    values: ['saudi', 'Saudi'],
    aliases: [
      'saudi',
      'saud',
      'arabiston',
      'saudiya',
      'saudiya arabiston',
      'arabcha',
      'саудовская аравия',
      'саудовский',
      'саудовские',
    ],
  },
  {
    values: ['egypt', 'Egypt'],
    aliases: [
      'egypt',
      'misr',
      'egyptian',
      'misrlik',
      'египет',
      'египетский',
      'египетские',
    ],
  },
  {
    values: ['uae', 'UAE'],
    aliases: [
      'uae',
      'dubai',
      'arab amirliklari',
      'emirates',
      'abu dabi',
      'dubaycha',
      'оаэ',
      'дубай',
      'эмираты',
      'арабские эмираты',
    ],
  },
  {
    values: ['Turkey', 'turkey', 'turkiya'],
    aliases: [
      'turkey',
      'turkiya',
      'turk',
      'turukcha',
      'turkcha',
      'турция',
      'турецкий',
      'турецкие',
      'турецкое',
    ],
  },
  {
    values: ['japan', 'Japan'],
    aliases: [
      'japan',
      'yaponiya',
      'yapon',
      'yaponcha',
      'япония',
      'японский',
      'японские',
      'японское',
    ],
  },
  {
    values: ['qozogiston', "Qozog'iston", 'kazakhstan'],
    aliases: [
      'qozogiston',
      "qozog'iston",
      'qozoq',
      'qozoqcha',
      'kazakhstan',
      'казахстан',
      'казахский',
      'казахские',
      'казахское',
    ],
  },
  {
    values: ['ispaniya', 'spain', 'Spain', 'ispaniyacha', 'ispancha'],
    aliases: [
      'ispaniya',
      'spain',
      'ispancha',
      'ispaniyacha',
      'spanish',
      'ispaniyalik',
      'испания',
      'испанский',
      'испанские',
      'испанское',
    ],
  },
  {
    values: ['italiya', 'italy', 'Italy'],
    aliases: [
      'italiya',
      'italy',
      'italyan',
      'italyancha',
      'italian',
      'италия',
      'итальянский',
      'итальянские',
      'итальянское',
    ],
  },
  {
    values: ['germaniya', 'germany', 'Germany'],
    aliases: [
      'germaniya',
      'germany',
      'german',
      'nemis',
      'nemischa',
      'германия',
      'немецкий',
      'немецкие',
      'немецкое',
    ],
  },
  {
    values: ['fransiya', 'france', 'France'],
    aliases: [
      'fransiya',
      'france',
      'fransuz',
      'fransuzcha',
      'french',
      'франция',
      'французский',
      'французские',
      'французское',
    ],
  },
  {
    values: ['xitoy', 'china', 'China', 'Xitoy'],
    aliases: [
      'xitoy',
      'china',
      'xita',
      'xtoy',
      'chinese',
      'xitoycha',
      'китай',
      'китайский',
      'китайские',
      'китайское',
    ],
  },
  {
    values: ['india', 'India', 'hindiston'],
    aliases: [
      'india',
      'hind',
      'hindiston',
      'hindcha',
      'indian',
      'индия',
      'индийский',
      'индийские',
      'индийское',
    ],
  },
  {
    values: ['braziliya', 'brazil', 'Brazil'],
    aliases: [
      'braziliya',
      'brazil',
      'brazilian',
      'braziliyalik',
      'бразилия',
      'бразильский',
      'бразильские',
    ],
  },
  {
    values: ['meksika', 'mexico', 'Mexico'],
    aliases: [
      'meksika',
      'mexico',
      'mexican',
      'meksikacha',
      'мексика',
      'мексиканский',
      'мексиканские',
    ],
  },
  {
    values: ['argentina', 'Argentina'],
    aliases: [
      'argentina',
      'argentinacha',
      'argentinalik',
      'аргентина',
      'аргентинский',
      'аргентинские',
    ],
  },
  {
    values: ['avstraliya', 'australia', 'Australia'],
    aliases: [
      'avstraliya',
      'australia',
      'avstraliyalik',
      'австралия',
      'австралийский',
      'австралийские',
    ],
  },
  {
    values: ['niderlandiya', 'netherlands', 'Holland'],
    aliases: [
      'niderlandiya',
      'netherlands',
      'gollandiya',
      'holland',
      'dutch',
      'нидерланды',
      'голландия',
      'голландский',
      'голландские',
    ],
  },
  {
    values: ['shvetsiya', 'sweden', 'Sweden'],
    aliases: [
      'shvetsiya',
      'sweden',
      'shved',
      'swedish',
      'швеция',
      'шведский',
      'шведские',
    ],
  },
  {
    values: ['norvegiya', 'norway', 'Norway'],
    aliases: [
      'norvegiya',
      'norway',
      'norwegian',
      'норвегия',
      'норвежский',
      'норвежские',
    ],
  },
  {
    values: ['finlyandiya', 'finland', 'Finland'],
    aliases: [
      'finlyandiya',
      'finland',
      'finnish',
      'fin',
      'финляндия',
      'финский',
      'финские',
    ],
  },
  {
    values: ['polsha', 'poland', 'Poland'],
    aliases: [
      'polsha',
      'poland',
      'polish',
      'polyak',
      'польша',
      'польский',
      'польские',
    ],
  },
  {
    values: ['ukraina', 'ukraine', 'Ukraine'],
    aliases: [
      'ukraina',
      'ukraine',
      'ukraincha',
      'ukrainian',
      'украина',
      'украинский',
      'украинские',
    ],
  },
  {
    values: ['belarus', 'Belarus'],
    aliases: [
      'belarus',
      'belorussiya',
      'belaruscha',
      'беларусь',
      'белоруссия',
      'белорусский',
      'белорусские',
    ],
  },
  {
    values: ['ozarbayjon', 'azerbaijan', 'Azerbaijan'],
    aliases: [
      'ozarbayjon',
      'azerbaijan',
      'ozarbayjoncha',
      'азербайджан',
      'азербайджанский',
      'азербайджанские',
    ],
  },
  {
    values: ['gruziya', 'georgia', 'Georgia'],
    aliases: [
      'gruziya',
      'georgia',
      'gruzin',
      'gruzinch',
      'грузия',
      'грузинский',
      'грузинские',
    ],
  },
  {
    values: ['armaniston', 'armenia', 'Armenia'],
    aliases: [
      'armaniston',
      'armenia',
      'arman',
      'armancha',
      'армения',
      'армянский',
      'армянские',
    ],
  },
  {
    values: ['tojikiston', 'tajikistan', 'Tajikistan'],
    aliases: [
      'tojikiston',
      'tajikistan',
      'tojik',
      'tojikcha',
      'таджикистан',
      'таджикский',
      'таджикские',
    ],
  },
  {
    values: ['qirgiziston', 'kyrgyzstan', 'Kyrgyzstan'],
    aliases: [
      'qirgiziston',
      'kyrgyzstan',
      'qirgiz',
      'qirgizcha',
      'кыргызстан',
      'киргизия',
      'киргизский',
      'киргизские',
    ],
  },
  {
    values: ['turkmaniston', 'turkmenistan', 'Turkmenistan'],
    aliases: [
      'turkmaniston',
      'turkmenistan',
      'turkman',
      'turkmancha',
      'туркменистан',
      'туркменский',
      'туркменские',
    ],
  },
  {
    values: ['pokiston', 'pakistan', 'Pakistan'],
    aliases: [
      'pokiston',
      'pakistan',
      'pokistoncha',
      'пакистан',
      'пакистанский',
      'пакистанские',
    ],
  },
  {
    values: ['eron', 'iran', 'Iran'],
    aliases: [
      'eron',
      'iran',
      'fors',
      'persian',
      'eroncha',
      'иран',
      'иранский',
      'иранские',
      'персидский',
    ],
  },
  {
    values: ['iraq', 'Iraq'],
    aliases: [
      'iraq',
      'iroq',
      'iraqi',
      'ирак',
      'иракский',
      'иракские',
    ],
  },
  {
    values: ['marokash', 'morocco', 'Morocco'],
    aliases: [
      'marokash',
      'morocco',
      'moroccan',
      'марокко',
      'марокканский',
      'марокканские',
    ],
  },
  {
    values: ['nigeriya', 'nigeria', 'Nigeria'],
    aliases: [
      'nigeriya',
      'nigeria',
      'nigerian',
      'нигерия',
      'нигерийский',
      'нигерийские',
    ],
  },
  {
    values: ['janubiy afrika', 'south africa', 'South Africa'],
    aliases: [
      'janubiy afrika',
      'south africa',
      'safrica',
      'юар',
      'южная африка',
      'южноафриканский',
    ],
  },
  {
    values: ['tailand', 'thailand', 'Thailand', 'Tailand'],
    aliases: [
      'tailand',
      'thailand',
      'tayland',
      'tailandcha',
      'taylandcha',
      'таиланд',
      'тайский',
      'тайские',
      'тайское',
    ],
  },
  {
    values: ['vetnam', 'vietnam', 'Vietnam'],
    aliases: [
      'vetnam',
      'vietnam',
      'vietnamese',
      'вьетнам',
      'вьетнамский',
      'вьетнамские',
    ],
  },
  {
    values: ['indoneziya', 'indonesia', 'Indonesia'],
    aliases: [
      'indoneziya',
      'indonesia',
      'indonesian',
      'индонезия',
      'индонезийский',
      'индонезийские',
    ],
  },
  {
    values: ['malaysia', 'Malaysia', 'malayziya'],
    aliases: [
      'malaysia',
      'malayziya',
      'malaysian',
      'малайзия',
      'малайзийский',
      'малайзийские',
    ],
  },
  {
    values: ['filippin', 'philippines', 'Philippines'],
    aliases: [
      'filippin',
      'philippines',
      'filippincha',
      'филиппины',
      'филиппинский',
      'филиппинские',
    ],
  },
  {
    values: ['singapur', 'singapore', 'Singapore'],
    aliases: [
      'singapur',
      'singapore',
      'сингапур',
      'сингапурский',
    ],
  },
  {
    values: ['gretsiya', 'greece', 'Greece'],
    aliases: [
      'gretsiya',
      'greece',
      'greek',
      'yunon',
      'греция',
      'греческий',
      'греческие',
    ],
  },
  {
    values: ['portugaliya', 'portugal', 'Portugal'],
    aliases: [
      'portugaliya',
      'portugal',
      'portuguese',
      'португалия',
      'португальский',
      'португальские',
    ],
  },
  {
    values: ['shveytsariya', 'switzerland', 'Switzerland'],
    aliases: [
      'shveytsariya',
      'switzerland',
      'swiss',
      'швейцария',
      'швейцарский',
      'швейцарские',
    ],
  },
  {
    values: ['avstriya', 'austria', 'Austria'],
    aliases: [
      'avstriya',
      'austria',
      'austrian',
      'австрия',
      'австрийский',
      'австрийские',
    ],
  },
  {
    values: ['belgiya', 'belgium', 'Belgium'],
    aliases: [
      'belgiya',
      'belgium',
      'belgian',
      'бельгия',
      'бельгийский',
      'бельгийские',
    ],
  },
  {
    values: ['irlandiya', 'ireland', 'Ireland'],
    aliases: [
      'irlandiya',
      'ireland',
      'irish',
      'ирландия',
      'ирландский',
      'ирландские',
    ],
  },
  {
    values: ['shotlandiya', 'scotland', 'Scotland'],
    aliases: [
      'shotlandiya',
      'scotland',
      'scottish',
      'шотландия',
      'шотландский',
      'шотландские',
    ],
  },
  {
    values: ['kolumbiya', 'colombia', 'Colombia'],
    aliases: [
      'kolumbiya',
      'colombia',
      'colombian',
      'колумбия',
      'колумбийский',
      'колумбийские',
    ],
  },
  {
    values: ['chili', 'chile', 'Chile'],
    aliases: [
      'chili',
      'chile',
      'chilean',
      'чили',
      'чилийский',
      'чилийские',
    ],
  },
  {
    values: ['kuba', 'cuba', 'Cuba'],
    aliases: [
      'kuba',
      'cuba',
      'cuban',
      'куба',
      'кубинский',
      'кубинские',
    ],
  },
  {
    values: ['yamayka', 'jamaica', 'Jamaica'],
    aliases: [
      'yamayka',
      'jamaica',
      'jamaican',
      'ямайка',
      'ямайский',
      'ямайские',
    ],
  },
  {
    values: ['isroil', 'israel', 'Israel'],
    aliases: [
      'isroil',
      'israel',
      'israeli',
      'израиль',
      'израильский',
      'израильские',
    ],
  },
  {
    values: ['livan', 'lebanon', 'Lebanon'],
    aliases: [
      'livan',
      'lebanon',
      'lebanese',
      'ливан',
      'ливанский',
      'ливанские',
    ],
  },
  {
    values: ['iordaniya', 'jordan', 'Jordan'],
    aliases: [
      'iordaniya',
      'jordan',
      'jordanian',
      'иордания',
      'иорданский',
      'иорданские',
    ],
  },
  {
    values: ['quvayt', 'kuwait', 'Kuwait'],
    aliases: [
      'quvayt',
      'kuwait',
      'кувейт',
      'кувейтский',
    ],
  },
  {
    values: ['qatar', 'Qatar'],
    aliases: [
      'qatar',
      'qatarlik',
      'катар',
      'катарский',
    ],
  },
  {
    values: ['bahrayn', 'bahrain', 'Bahrain'],
    aliases: [
      'bahrayn',
      'bahrain',
      'бахрейн',
    ],
  },
  {
    values: ['oman', 'Oman'],
    aliases: [
      'oman',
      'оман',
    ],
  },
  {
    values: ['mongoliya', 'mongolia', 'Mongolia'],
    aliases: [
      'mongoliya',
      'mongolia',
      'mongol',
      'монголия',
      'монгольский',
      'монгольские',
    ],
  },
  {
    values: ['afgoniston', 'afghanistan', 'Afghanistan'],
    aliases: [
      'afgoniston',
      'afghanistan',
      'afgon',
      'афганистан',
      'афганский',
      'афганские',
    ],
  },
  {
    values: ['bangladesh', 'Bangladesh'],
    aliases: [
      'bangladesh',
      'bangladeshcha',
      'бангладеш',
    ],
  },
  {
    values: ['nepal', 'Nepal'],
    aliases: [
      'nepal',
      'nepalcha',
      'непал',
      'непальский',
    ],
  },
  {
    values: ['shri lanka', 'sri lanka', 'Sri Lanka'],
    aliases: [
      'shri lanka',
      'sri lanka',
      'srilanka',
      'шри-ланка',
      'шри ланка',
    ],
  },
  {
    values: ['yangilandiya', 'new zealand', 'New Zealand'],
    aliases: [
      'yangilandiya',
      'new zealand',
      'newzealand',
      'новая зеландия',
      'новозеландский',
    ],
  },
]


/** DB music.genre qiymatlari + foydalanuvchi sinonimlari */


const MEDIA_GENRE_FACETS = [
  {
    values: ['electronic', 'Electronic'],
    aliases: [
      'electronic',
      'elektron',
      'elektronika',
      'edm',
      'elektron musiqa',
      'электронная',
      'электроника',
      'электронная музыка',
      'эдм',
    ],
  },
  {
    values: ['dubstep'],
    aliases: [
      'dubstep',
      'dabstep',
      'dub step',
      'дабстеп',
    ],
  },
  {
    values: ['bass'],
    aliases: [
      'bass',
      'bes',
      'deep bass',
      'бас',
      'басс',
      'дип бас',
    ],
  },
  {
    values: ['pop'],
    aliases: [
      'pop',
      'pop musiqa',
      'pop music',
      'поп',
      'поп музыка',
      'поп-музыка',
    ],
  },
  {
    values: ['k-pop', 'kpop', 'k pop', 'K-pop', 'karischa pop', 'karis pop'],
    aliases: [
      'k-pop',
      'kpop',
      'k pop',
      'korean pop',
      'koreys pop',
      'karischa pop',
      'karis pop',
      'к-поп',
      'кейпоп',
      'корейский поп',
    ],
  },
  {
    values: ['j-pop', 'jpop', 'J-pop'],
    aliases: [
      'j-pop',
      'jpop',
      'j pop',
      'japanese pop',
      'yapon pop',
      'дж-поп',
      'джейпоп',
      'японский поп',
    ],
  },
  {
    values: ['hip-hop', 'Rap'],
    aliases: [
      'hip-hop',
      'hiphop',
      'hip hop',
      'rap',
      'rep',
      'repp',
      'hip-hop musiqa',
      'хип-хоп',
      'хипхоп',
      'рэп',
      'рэп музыка',
    ],
  },
  {
    values: ['trap'],
    aliases: [
      'trap',
      'trap musiqa',
      'трэп',
      'трап',
    ],
  },
  {
    values: ['drill'],
    aliases: [
      'drill',
      'drill musiqa',
      'дрилл',
    ],
  },
  {
    values: ['phonk'],
    aliases: [
      'phonk',
      'fonk',
      'фонк',
    ],
  },
  {
    values: ['jazz'],
    aliases: [
      'jazz',
      'jaz',
      'jazz musiqa',
      'джаз',
      'джазовая',
    ],
  },
  {
    values: ['Rock'],
    aliases: [
      'rock',
      'rok',
      'rock musiqa',
      'рок',
      'рок музыка',
    ],
  },
  {
    values: ['hard rock', 'Hard Rock'],
    aliases: [
      'hard rock',
      'hardrok',
      'qattiq rok',
      'хард рок',
      'тяжелый рок',
    ],
  },
  {
    values: ['metal', 'Metal'],
    aliases: [
      'metal',
      'metall',
      'heavy metal',
      'hevi metal',
      'метал',
      'металл',
      'хеви метал',
    ],
  },
  {
    values: ['punk', 'Punk'],
    aliases: [
      'punk',
      'pank',
      'punk rock',
      'панк',
      'панк рок',
    ],
  },
  {
    values: ['alternative', 'Alternative'],
    aliases: [
      'alternative',
      'alternativ',
      'alt rock',
      'альтернатива',
      'альтернативный рок',
    ],
  },
  {
    values: ['indie', 'Indie'],
    aliases: [
      'indie',
      'indi',
      'indie musiqa',
      'инди',
      'инди музыка',
    ],
  },
  {
    values: ['grunge'],
    aliases: [
      'grunge',
      'granj',
      'гранж',
    ],
  },
  {
    values: ['nasheed'],
    aliases: [
      'nasheed',
      'nashid',
      'islomiy',
      'islamic',
      'нашид',
      'нашиды',
      'исламская',
    ],
  },
  {
    values: ['opera'],
    aliases: [
      'opera',
      'opera musiqa',
      'опера',
      'оперная',
    ],
  },
  {
    values: ['classical', 'Classical'],
    aliases: [
      'classical',
      'klassik',
      'klassika',
      'klassik musiqa',
      'classic',
      'klassic',
      'kliccika',
      'klaccik',
      'gamgin',
      "g'amgin",
      'ghamgin',
      'классика',
      'классическая',
      'классическая музыка',
    ],
  },
  {
    values: ['blues', 'Blues'],
    aliases: [
      'blues',
      'blyuz',
      'blues musiqa',
      'gamgin',
      "g'amgin",
      'ghamgin',
      'блюз',
    ],
  },
  {
    values: ['reggae', 'Reggae'],
    aliases: [
      'reggae',
      'reggi',
      'rege',
      'регги',
    ],
  },
  {
    values: ['r&b', 'rnb', 'R&B', 'RnB'],
    aliases: [
      'r&b',
      'rnb',
      'r and b',
      'rhythm and blues',
      'ар эн би',
      'ритм энд блюз',
    ],
  },
  {
    values: ['soul', 'Soul'],
    aliases: [
      'soul',
      'soul musiqa',
      'соул',
    ],
  },
  {
    values: ['funk', 'Funk'],
    aliases: [
      'funk',
      'fank',
      'фанк',
    ],
  },
  {
    values: ['disco', 'Disco'],
    aliases: [
      'disco',
      'disko',
      'disco musiqa',
      'диско',
    ],
  },
  {
    values: ['house', 'House'],
    aliases: [
      'house',
      'haus',
      'house musiqa',
      'хаус',
    ],
  },
  {
    values: ['techno', 'Techno'],
    aliases: [
      'techno',
      'texno',
      'techno musiqa',
      'техно',
    ],
  },
  {
    values: ['trance', 'Trance'],
    aliases: [
      'trance',
      'trans',
      'транс',
    ],
  },
  {
    values: ['drum and bass', 'dnb', 'DnB'],
    aliases: [
      'drum and bass',
      'dnb',
      'drum n bass',
      'drumnbass',
      'драм энд бейс',
      'драмнбейс',
    ],
  },
  {
    values: ['ambient', 'Ambient'],
    aliases: [
      'ambient',
      'ambient musiqa',
      'эмбиент',
    ],
  },
  {
    values: ['lofi', 'lo-fi', 'Lo-Fi'],
    aliases: [
      'lofi',
      'lo-fi',
      'lo fi',
      'lofay',
      'лоуфай',
      'ло-фай',
    ],
  },
  {
    values: ['chill', 'chillout', 'Chill'],
    aliases: [
      'chill',
      'chillout',
      'chill out',
      'rilaks',
      'чилл',
      'чиллаут',
    ],
  },
  {
    values: ['synthwave', 'Synthwave'],
    aliases: [
      'synthwave',
      'sintveyv',
      'retrowave',
      'синтвейв',
      'ретrowave',
      'ретровэйв',
    ],
  },
  {
    values: ['folk', 'Folk'],
    aliases: [
      'folk',
      'folklor',
      'xalq',
      'xalq musiqa',
      'folk musiqa',
      'фолк',
      'народная',
      'народная музыка',
    ],
  },
  {
    values: ['country', 'Country'],
    aliases: [
      'country music',
      'kantri',
      'country musiqa',
      'kantri musiqa',
      'кантри',
    ],
  },
  {
    values: ['traditional', 'Traditional'],
    aliases: [
      'traditional',
      'ananaviy',
      "an'anaviy",
      'milliy',
      'milliy musiqa',
      'традиционная',
      'традиционная музыка',
      'национальная',
    ],
  },
  {
    values: ['maqom', 'Maqom'],
    aliases: [
      'maqom',
      'makom',
      'maqom musiqa',
      'маком',
      'маком музыка',
    ],
  },
  {
    values: ['estrada', 'Estrada'],
    aliases: [
      'estrada',
      'estrada musiqa',
      'эстрада',
      'эстрадная',
    ],
  },
  {
    values: ['latin', 'Latin', 'Latino'],
    aliases: [
      'latin',
      'latino',
      'latina',
      'lotin',
      'latin musiqa',
      'латинская',
      'латино',
      'латина',
    ],
  },
  {
    values: ['salsa', 'Salsa'],
    aliases: [
      'salsa',
      'salsa musiqa',
      'сальса',
    ],
  },
  {
    values: ['reggaeton', 'Reggaeton'],
    aliases: [
      'reggaeton',
      'reggeton',
      'regeton',
      'реггетон',
    ],
  },
  {
    values: ['flamenco', 'Flamenco'],
    aliases: [
      'flamenco',
      'flamenko',
      'фламенко',
    ],
  },
  {
    values: ['tango', 'Tango'],
    aliases: [
      'tango',
      'tango musiqa',
      'танго',
    ],
  },
  {
    values: ['samba', 'Samba'],
    aliases: [
      'samba',
      'самба',
    ],
  },
  {
    values: ['bossa nova', 'Bossa Nova'],
    aliases: [
      'bossa nova',
      'bossanova',
      'bossa',
      'босса нова',
      'боссанова',
    ],
  },
  {
    values: ['afrobeat', 'Afrobeats'],
    aliases: [
      'afrobeat',
      'afrobeats',
      'afro beat',
      'афробит',
      'афробитс',
    ],
  },
  {
    values: ['arabic', 'Arabic', 'arab'],
    aliases: [
      'arabic',
      'arab',
      'arabcha musiqa',
      'arab musiqa',
      'арабская',
      'арабская музыка',
      'арабский',
    ],
  },
  {
    values: ['arabesk', 'Arabesk'],
    aliases: [
      'arabesk',
      'arabeska',
      'арабеска',
      'арабеск',
    ],
  },
  {
    values: ['shanson', 'chanson', 'Shanson'],
    aliases: [
      'shanson',
      'chanson',
      'shanson musiqa',
      'шансон',
    ],
  },
  {
    values: ['gospel', 'Gospel'],
    aliases: [
      'gospel',
      'gospel musiqa',
      'госпел',
    ],
  },
  {
    values: ['dance', 'Dance'],
    aliases: [
      'dance',
      'dans',
      'raqs',
      'dance musiqa',
      'raqs musiqa',
      'танцевальная',
      'данс',
      'танцевальная музыка',
    ],
  },
  {
    values: ['ballad', 'Ballad'],
    aliases: [
      'ballad',
      'ballada',
      'ballad musiqa',
      'gamgin',
      "g'amgin",
      'ghamgin',
      'баллада',
      'баллады',
    ],
  },
  {
    values: ['romance', 'Romance'],
    aliases: [
      'romance',
      'romans',
      'romantik',
      'romantik musiqa',
      'gamgin',
      "g'amgin",
      'ghamgin',
      'романс',
      'романсы',
      'романтическая',
    ],
  },
  {
    values: ['acoustic', 'Acoustic'],
    aliases: [
      'acoustic',
      'akustik',
      'akustika',
      'акустика',
      'акустическая',
    ],
  },
  {
    values: ['instrumental', 'Instrumental'],
    aliases: [
      'instrumental',
      'instrumental musiqa',
      'sozsiz',
      'инструментал',
      'инструментальная',
    ],
  },
  {
    values: ['soundtrack', 'OST', 'ost'],
    aliases: [
      'soundtrack',
      'ost',
      'saundtrek',
      'film musiqa',
      'саундтрек',
      'саундтреки',
      'музыка из фильма',
    ],
  },
  {
    values: ['world', 'World'],
    aliases: [
      'world',
      'world music',
      'jahon musiqa',
      'мировая музыка',
    ],
  },
  {
    values: ['children', 'Kids'],
    aliases: [
      'children',
      'kids',
      'bolalar',
      'bolalar musiqa',
      'child',
      'детская',
      'детская музыка',
      'для детей',
    ],
  },
]

module.exports = {
  MEDIA_COUNTRY_FACETS,
  MEDIA_GENRE_FACETS,
};
