
export const artists = [
  {
    id: 'jah-khalib',
    img: '/img/movie1.jpg',
    imgArtist: '/img/movie1.jpg',
    name: 'Jah Khalib',
    description: 'Qozog‘istonlik mashhur R&B va hip-hop qo‘shiqchisi, zamonaviy ovoz ustasi.',
    subscribers: 12,
    birthDate: '1990-02-16',
    country: "Qozog'iston",
    city: 'Almati',
    genres: ['R&B', 'Pop', 'Soul'],
    bio: {
      text: 'Jah Khalib (Bakir Mustafayev) 1990-yilda Qozog‘istonda tug‘ilgan. U R&B, hip-hop va pop janrlarida ijod qiladi. 2015-yilda chiqqan "Leyla" qo‘shig‘i bilan mashhurlikka erishdi. Albomlari: "Leyla", "Honey" va boshqalar. Qozog‘istonning eng taniqli zamonaviy qo‘shiqchilaridan biri sifatida tanilgan. O‘zining romantik va chuqur so‘zlari bilan millionlab muxlislarni o‘ziga jalb qildi. Konsertlari butun MDH mamlakatlarida katta muvaffaqiyat qozonadi. Musiqiy faoliyatini 2014-yilda boshlagan. Birinchi studiyaviy albomi "Inner Thoughts" 2015-yilda chiqdi. "Leyla" qo‘shig‘i YouTube da yuz milliondan ortiq ko‘rilgan. Turli xalqaro mukofotlar va nominatsiyalarga sazovor bo‘lgan. Hozirda Qozog‘iston, Rossiya, O‘zbekiston va boshqa mamlakatlarda kontsertlar beradi. Jah Khalib 1990-yil 16-fevralda Olmaota shahrida tavallud topgan. U bolaligidan musiqaga qiziqish bildirgan va maktab yillarida gitarada chalishni o‘rgangan. 2014-yilda "Siniy Fiat" qo‘shig‘i orqali keng omma e‘tiboriga tushdi. Keyingi yillarda "Leyla", "Medina", "Vdox-Vidox" kabi hit qo‘shiqlar yozdi. 2018-yilda "Honey" albomini chiqarib, yana bir bor o‘zining professional darajasini ko‘rsatdi. Uning qo‘shiqlari romantika, muhabbat va hayotiy mavzularga bag‘ishlangan. Jah Khalib turli xalqaro festivallarda, jumladan Almati, Moskva, Toshkent, Boku kabi shaharlarda kontsertlar bergan. U R&B va hip-hopni o‘zbek, rus va qozoq tillarida uyg‘unlashtirib ijod qiladi.',
      bioImg: ['/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg', '/img/movie1.jpg', '/img/movie1.jpg', '/img/movie1.jpg'],
    },
    photoGallery: ['/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg'],
  },
  {
    id: 'shohruhxon',
    img: '/img/movie2.jpg',
    imgArtist: '/img/movie2.jpg',
    name: 'Shohruhxon',
    description: 'O‘zbekistonning taniqli qo‘shiqchisi, romantik va zamonaviy qo‘shiqlar ijrochisi.',
    subscribers: 98000,
    birthDate: '1988-05-12',
    country: "O'zbekiston",
    city: 'Toshkent',
    genres: ['Pop', 'Ballada'],
    bio: {
      text: 'Shohruhxon — O‘zbekistonning taniqli qo‘shiqchisi. Romantik va zamonaviy qo‘shiqlar ijrochisi. Bir nechta hit qo‘shiqlari orqali o‘z muxlislarini topdi.',
      bioImg: ['/img/movie2.jpg', '/img/movie1.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg', '/img/movie2.jpg', '/img/movie2.jpg'],
    },
    photoGallery: ['/img/movie2.jpg', '/img/movie1.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg'],
  },
  {
    id: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    imgArtist: '/img/movie-4.5-1.avif',
    name: 'Michael Jackson',
    description: 'American singer, songwriter, dancer. The King of Pop.',
    subscribers: 25000000,
    birthDate: '1958-08-29',
    country: 'USA',
    city: 'Gary, Indiana',
    genres: ['Pop', 'R&B', 'Soul'],
    bio: {
      text: 'Michael Jackson (1958–2009) — dunyoning eng mashhur pop yulduzi. "Thriller", "Bad", "Off the Wall" kabi albomlari rekordlar o‘rnatdi. King of Pop laqabi bilan tanilgan.',
      bioImg: ['/img/movie-4.5-1.avif', '/img/movie1.jpg', '/img/movie2.jpg', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg', '/img/movie-4.5-1.avif'],
    },
    photoGallery: ['/img/movie-4.5-1.avif', '/img/movie1.jpg', '/img/movie2.jpg', '/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg'],
  },
  {
    id: 'maher-zain',
    img: '/img/nasheedsimg1.jpg',
    imgArtist: '/img/nasheedsimg1.jpg',
    name: 'Maher Zain',
    description: 'Shvediya tug\'ilgan nasheed ijrochisi, islamiy ilohiy qo\'shiqlar ustasi.',
    subscribers: 5200000,
    birthDate: '1981-07-16',
    country: 'Shvetsiya',
    city: 'Tripoli',
    genres: ['Nasheed', 'Pop', 'R&B'],
    bio: {
      text: 'Maher Zain — Shvetsiyada tug‘ilgan libbiyalik nasheed ijrochisi. "Forgive Me", "Insha Allah" kabi qo‘shiqlari bilan butun dunyoda tanilgan.',
      bioImg: ['/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg', '/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg1.jpg'],
    },
    photoGallery: ['/img/nasheedsimg1.jpg', '/img/nasheedsimg2.jpg', '/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif'],
  },
  {
    id: 'sami-yusuf',
    img: '/img/nasheedsimg2.jpg',
    imgArtist: '/img/nasheedsimg2.jpg',
    name: 'Sami Yusuf',
    description: 'Britaniya tug\'ilgan nasheed ijrochisi, zamonaviy islamiy musiqa yetakchisi.',
    subscribers: 4800000,
    birthDate: '1980-07-19',
    country: 'Birlashgan Qirollik',
    city: 'London',
    genres: ['Nasheed', 'Pop'],
    bio: {
      text: 'Sami Yusuf — Londonda tug‘ilgan britaniyalik nasheed ijrochisi. "Al-Mu‘allim", "Hasbi Rabbi" qo‘shiqlari bilan mashhur. Zamonaviy islamiy musiqa yetakchisi.',
      bioImg: ['/img/nasheedsimg2.jpg', '/img/nasheedsimg1.jpg', '/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif', '/img/nasheedsimg2.jpg'],
    },
    photoGallery: ['/img/nasheedsimg2.jpg', '/img/nasheedsimg1.jpg', '/img/movie1.jpg', '/img/movie2.jpg', '/img/movie-4.5-1.avif'],
  },
];
