/**
 * Bass Music - Bass musiqa bo'limi uchun ma'lumotlar.
 * type: 'music' - audio trek.
 */
export const bassMusicData = [
  {
    id: 801,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Deep Bass',
    year: 2025,
    genre: 'electronic',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Chuqur bass - jonimga\nDeep bass - titrash\nHar bir beat - hayot",
  },
  {
    id: 802,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Subwoofer',
    year: 2024,
    genre: 'dubstep',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Subwoofer - yuragim titraydi\nKuchli ovoz - sensiz emas\nBu kecha - bizniki",
  },
  {
    id: 803,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Bass Drop',
    year: 2023,
    genre: 'electronic',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Bass drop - moment\nHar bir drop - hayajon\nAbadiy kecha",
  },
  {
    id: 804,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: 'Low Frequency',
    year: 2024,
    genre: 'bass',
    language: 'russian',
    country: 'russia',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Past chastota - titrash\nLow frequency - sensiz emas\nShahar kechasi",
  },
  {
    id: 805,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Heavy Bass',
    year: 2022,
    genre: 'dubstep',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Og'ir bass - kuchli\nHeavy bass - menga yo'ldosh\nHar kecha",
  },
  {
    id: 806,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Bassline',
    year: 2025,
    genre: 'electronic',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Bass chizig'i - ritm\nBassline - hayot\nBu dunyo - bizniki",
  },
  {
    id: 807,
    artistId: 'michael-jackson',
    img: '/img/movie1.jpg',
    title: 'Earthquake',
    year: 2023,
    genre: 'dubstep',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Zilzila - bass ostida\nEarthquake - titrash\nAbadiy moment",
  },
  {
    id: 808,
    artistId: 'shohruhxon',
    img: '/img/movie2.jpg',
    title: 'Bass Cannon',
    year: 2024,
    genre: 'electronic',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Bass to'pi - kuchli\nBass cannon - sensiz emas\nHar bir kecha",
  },
  {
    id: 809,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Sub Bass',
    year: 2022,
    genre: 'bass',
    language: 'english',
    country: 'kanada',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Sub bass - chuqur\nYuragim titraydi\nSen bilan",
  },
  {
    id: 810,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Bass Boost',
    year: 2025,
    genre: 'electronic',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Bass kuchaytirish - hayajon\nBass boost - kecha\nAbadiy",
  },
  {
    id: 811,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Rumble',
    year: 2023,
    genre: 'dubstep',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "G'ovur - bass ostida\nRumble - titrash\nBu kecha - sensiz emas",
  },
];
