/**
 * Discover Music - Musiqani kashf eting bo'limi uchun ma'lumotlar.
 * type: 'music' - audio trek.
 */
export const discoverMusicData = [
  {
    id: 501,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Face love',
    year: 2025,
    genre: 'pop',
    language: 'korean',
    country: 'korea',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman",
  },
  {
    id: 502,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Summer Vibes',
    year: 2024,
    genre: 'pop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Yozning har bir kuni yorug'\nSensiz bo'lmasa ham yorug'\nOq tunlar va yulduzlar\nSenga qarab kutaman",
  },
  {
    id: 503,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: 'Night Drive',
    year: 2023,
    genre: 'hip-hop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Tungi yo'llarda hayoling\nBarcha narsani unutding\nMashina tez, yulduzlar sez\nBu kecha - bizniki",
  },
  {
    id: 504,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Moonlight',
    year: 2022,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Oydin kechada yolg'iz\nSening so'zlaringni eslayman\nMoonlight - sening ko'zlaring\nMen uchun yorug'lik",
  },
  {
    id: 505,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Dream State',
    year: 2024,
    genre: 'electronic',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Tushda ko'rdim seni\nUyg'onib qoldim yolg'iz\nDream state - haqiqat emas\nLekin sensiz emas",
  },
  {
    id: 506,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'City Lights',
    year: 2023,
    genre: 'Rap',
    language: 'russian',
    country: 'russia',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Shahar chiroqlari yoniq\nHar bir ko'cha - yangi dunyo\nCity lights - sening yo'ling\nMen ham boraman",
  },
  {
    id: 507,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Ocean View',
    year: 2022,
    genre: 'pop',
    language: 'english',
    country: 'kanada',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Okean oldida turibman\nTolqinlar - sening ovozing\nOcean view - abadiy\nSenga qarab yashayman",
  },
  {
    id: 508,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-3.jpg',
    title: 'Golden Hour',
    year: 2024,
    genre: 'jazz',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Oltin soat - quyosh botish\nEng chiroyli vaqt - sen bilan\nGolden hour - abadiy\nXotirangda qolaman",
  },
  {
    id: 509,
    artistId: 'shohruhxon',
    img: '/img/movie2.jpg',
    title: 'Rainy Days',
    year: 2021,
    genre: 'pop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Yomg'irli kunlar - sensiz\nHar bir tomchi - xotira\nRainy days - o'tib ketadi\nSen qolasan yuragimda",
  },
  {
    id: 510,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Starlight',
    year: 2023,
    genre: 'Rock',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Yulduzli tun - sening so'nging\nStarlight - menga yo'ldosh\nOlamning narigi tomonida\nSen bilan bo'laman",
  },
];
