/**
 * Love and Desire (Sevgi va ichq) - video clip section data.
 * type: 'klip' - video content.
 */
export const loveAndDesireData = [
  { id: 1101, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-1.avif', title: 'Die With A Smile', year: 2024, genre: 'pop', language: 'english', country: 'usa', type: 'klip', video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4', like: '0', dislike: '0' },
  { id: 1102, categoryNameMusic: 'liveStagesData', artistId: 'shohruhxon', img: '/img/movie-4.5-2.jpeg', title: 'The Amateur', year: 2024, genre: 'drama', language: 'english', country: 'usa', type: 'klip', video: '/video/The Amateur _ Official Trailer.mp4', like: '0', dislike: '0' },
  { id: 1103, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-3.jpg', title: 'Life', year: 2020, genre: 'pop', language: 'russian', country: 'russia', type: 'klip', video: '/video/Zivert - Life   Премьера клипа.mp4', like: '0', dislike: '0' },
  { id: 1104, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-4.webp', title: 'Die With A Smile (Live)', year: 2024, genre: 'pop', language: 'english', country: 'usa', type: 'klip', video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4', like: '0', dislike: '0' },
  { id: 1105, categoryNameMusic: 'liveStagesData', artistId: 'shohruhxon', img: '/img/movie-4.5-5.jpg', title: 'The Amateur Trailer', year: 2024, genre: 'thriller', language: 'english', country: 'usa', type: 'klip', video: '/video/The Amateur _ Official Trailer.mp4', like: '0', dislike: '0' },
  { id: 1106, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-6.avif', title: 'Life - Premiere', year: 2020, genre: 'pop', language: 'russian', country: 'russia', type: 'klip', video: '/video/Zivert - Life   Премьера клипа.mp4', like: '0', dislike: '0' },
  { id: 1107, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-7.jpg', title: 'Die With A Smile - Official', year: 2024, genre: 'pop', language: 'english', country: 'usa', type: 'klip', video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4', like: '0', dislike: '0' },
  { id: 1108, categoryNameMusic: 'liveStagesData', artistId: 'shohruhxon', img: '/img/movie-4.5-8.jpg', title: 'The Amateur - Official Trailer', year: 2024, genre: 'drama', language: 'english', country: 'usa', type: 'klip', video: '/video/The Amateur _ Official Trailer.mp4', like: '0', dislike: '0' },
  { id: 1109, categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-9.jpg', title: 'Life - Zivert', year: 2020, genre: 'pop', language: 'russian', country: 'russia', type: 'klip', video: '/video/Zivert - Life   Премьера клипа.mp4', like: '0', dislike: '0' },
  { id: 1110, categoryNameMusic: 'liveStagesData', categoryNameMusic: 'liveStagesData', artistId: 'jah-khalib', img: '/img/movie-4.5-10.jpg', title: 'Die With A Smile - Music Video', year: 2024, genre: 'pop', language: 'english', country: 'usa', type: 'klip', video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4', like: '0', dislike: '0' },
  { id: 1111, categoryNameMusic: 'liveStagesData', artistId: 'shohruhxon', img: '/img/movie-4.5-2.jpeg', title: 'The Amateur', year: 2024, genre: 'romance', language: 'english', country: 'usa', type: 'klip', video: '/video/The Amateur _ Official Trailer.mp4', like: '0', dislike: '0' },
];
