/**
 * Music Library - Musiqa kutubxonasi bo'limi uchun ma'lumotlar.
 * type: 'music' - audio trek.
 */
export const musicLibraryData = [
  {
    id: 601,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Silent Night',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Jim tun - sen bilan\nYulduzlar - bizning guvohimiz\nSilent night - abadiy\nXotirangda qolaman",
  },
  {
    id: 602,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Old Town Road',
    year: 2023,
    genre: 'Rap',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Eski shahar yo'li\nHar bir qadam - tarix\nOld town road - menga yo'ldosh\nBorga boraman",
  },
  {
    id: 603,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Dancing Stars',
    year: 2022,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Raqs qilayotgan yulduzlar\nOsmon senga qarab\nDancing stars - kecha\nSen bilan raqs",
  },
  {
    id: 604,
    artistId: 'jah-khalib',
    img: '/img/movie2.jpg',
    title: 'Blue Skies',
    year: 2025,
    genre: 'electronic',
    language: 'english',
    country: 'britaniya',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Ko'k osmonlar - sening ko'zlaring\nBlue skies - menga yorug'lik\nHar kuni yangi boshlash\nSensiz emas",
  },
  {
    id: 605,
    artistId: 'shohruhxon',
    img: '/img/movie1.jpg',
    title: 'Winter Dreams',
    year: 2023,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Qish tushlari - oppoq\nWinter dreams - senga atalgan\nHar qor tomchi - xotira\nSen qolding",
  },
  {
    id: 606,
    artistId: 'jah-khalib',
    img: '/img/jah-khalib.jpg',
    title: 'Sunset Boulevard',
    year: 2024,
    genre: 'hip-hop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Quyosh botish bulvari\nSunset boulevard - bizniki\nQizil osmon ostida\nYana bir kecha",
  },
  {
    id: 607,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-2.jpeg',
    title: 'Electric Soul',
    year: 2022,
    genre: 'jazz',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Reed Wonder - When I Dream Of You.mp3',
    lyricsText: "Elektrik ruh - sening ovozing\nElectric soul - menga yo'ldosh\nHar bir nota - hayot\nSen ijro etding",
  },
  {
    id: 608,
    artistId: 'shohruhxon',
    img: '/img/movie2.jpg',
    title: 'Morning Light',
    year: 2021,
    genre: 'pop',
    language: 'uzbek',
    country: 'uzbekistan',
    type: 'music',
    audio: '/music/Chris Grey - WRONG (Official Lyric Video).mp3',
    lyricsText: "Ertalabki nur - sening tabassuming\nMorning light - yangi boshlash\nHar kuni - sovg'a\nSensiz emas",
  },
  {
    id: 609,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Neon Hearts',
    year: 2023,
    genre: 'Rock',
    language: 'english',
    country: 'kanada',
    type: 'music',
    audio: '/music/Zivert - Life.mp3',
    lyricsText: "Neon yuraklar - shahar kechasi\nNeon hearts - bizniki\nChiroqlar yonadi\nSen bilan",
  },
  {
    id: 610,
    artistId: 'michael-jackson',
    img: '/img/movie-4.5-1.avif',
    title: 'Paradise Lost',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'music',
    audio: '/music/Official Arctic Monkeys - I Wanna Be Yours.mp3',
    lyricsText: "Yo'qolgan jannat - sening qo'llaring\nParadise lost - topiladi\nQachon qaytsang\nMen kutaman",
  },
];
