/**
 * Music Drops - Albom bo'limi uchun ma'lumotlar.
 * Kartochka bosilsa MusicAlbumDetail sahifasiga chiqadi.
 */
export const musicDropsData = [
  {
    id: 801,
    title: "Top Hits 2025",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Kometa",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Alleya",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 3,
        title: "Kamin",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 802,
    title: "Summer Vibes",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Sunset",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Ocean",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 803,
    title: "Night Dreams",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2023,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Moonlight",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Stars",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 804,
    title: "Classic Collection",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2022,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Melody",
        artist: "Artist C",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 805,
    title: "Electric Soul",
    artist: "michael-jackson",
    artistId: 'michael-jackson',
    img: "/img/movie-4.5-2.jpeg",
    year: 2024,
    genre: 'jazz',
    language: 'english',
    country: 'usa',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Soul",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Electric",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
    ],
  },
  {
    id: 806,
    title: "Neon Hearts",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-3.jpg",
    year: 2023,
    genre: 'Rock',
    language: 'english',
    country: 'kanada',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Neon",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
      {
        id: 2,
        title: "Hearts",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 807,
    title: "Golden Hour",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/jah-khalib.jpg",
    year: 2024,
    genre: 'jazz',
    language: 'english',
    country: 'usa',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Golden",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 808,
    title: "City Lights",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2023,
    genre: 'Rap',
    language: 'russian',
    country: 'russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "City",
        artist: "Artist B",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Lights",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 809,
    title: "Ocean View",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie2.jpg",
    year: 2022,
    genre: 'pop',
    language: 'english',
    country: 'kanada',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Ocean",
        artist: "Jonny",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 810,
    title: "Starlight",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie-4.5-1.avif",
    year: 2024,
    genre: 'Rock',
    language: 'english',
    country: 'usa',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Star",
        artist: "Artist B",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
      {
        id: 2,
        title: "Light",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
    ],
  },
  {
    id: 811,
    title: "Dream State",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2025,
    genre: 'electronic',
    language: 'english',
    country: 'britaniya',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Dream",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "State",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
];
