/**
 * TopAlbums ma'lumotlari.
 * Albom kartochkasi bosilsa .music-detail-left-scroll sahifasiga chiqadi.
 * Boshqa albom kartochkalari .music-detail-right-scroll blokida ko'rsatiladi.
 */
export const TopAlbums = [
  {
    id: 1,
    title: "Top Hits 2025",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Kometa",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Alleya",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 3,
        title: "Kamin",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 2,
    title: "Summer Vibes",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Sunset",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Ocean",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 3,
    title: "Night Dreams",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2023,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Moonlight",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Stars",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 4,
    title: "Classic Collection",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2022,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Melody",
        artist: "Artist C",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  

  {
    id: 5,
    title: "Top Hits 2025",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Kometa",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Alleya",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 3,
        title: "Kamin",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 6,
    title: "Summer Vibes",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Sunset",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
        lyricsText: "Leyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman.\n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman \n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman.\n\nLeyla, Leyla, senga qarab yashayman\nOq tunlarni sensiz o'tkazaman\nLeyla, Leyla, yuragimni olib ketding\nQaytib kelishingni kutaman\n\nHar bir daqiqa sensiz o'tmas ekan\nKo'zlarim yoshlarga to'lib ketdi\nLeyla, sen menga kerak ekansan\nYana bir bor ko'rishni xohlayman",
      },
      {
        id: 2,
        title: "Ocean",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
        lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
      },
    ],
  },
  {
    id: 7,
    title: "Night Dreams",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2023,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Moonlight",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
        lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
      },
      {
        id: 2,
        title: "Stars",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
        lyricsText: "Medina, Medina, seni topmoqchiman\nShahar bo'ylab izlayman seni\nMedina, yuragimda yashaysan\nQachon ko'rishni istayman\n\nTungi yo'llarda yuringanman\nSening ovozingni eshitaman\nMedina, keling, qaytamiz\nBirlikda yashaymiz biz",
      },
    ],
  },
  {
    id: 8,
    title: "Classic Collection",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2022,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Melody",
        artist: "Artist C",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },

  {
    id: 9,
    title: "Top Hits 2025",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie1.jpg",
    year: 2025,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Kometa",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Alleya",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
      {
        id: 3,
        title: "Kamin",
        artist: "Jonny",
        audio: "/music/Chris Grey - WRONG (Official Lyric Video).mp3",
      },
    ],
  },
  {
    id: 10,
    title: "Summer Vibes",
    artist: "Jah Khalib",
    artistId: 'jah-khalib',
    img: "/img/movie2.jpg",
    year: 2024,
    genre: 'Rap',
    language: 'russian',
    country: 'Russia',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Sunset",
        artist: "Artist B",
        audio: "/music/Zivert - Life.mp3",
      },
      {
        id: 2,
        title: "Ocean",
        artist: "Artist B",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
  {
    id: 11,
    title: "Night Dreams",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie-4.5-2.jpeg",
    year: 2023,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Moonlight",
        artist: "Jonny",
        audio: "/music/Reed Wonder - When I Dream Of You.mp3",
      },
      {
        id: 2,
        title: "Stars",
        artist: "Jonny",
        audio: "/music/Zivert - Life.mp3",
      },
    ],
  },
  {
    id: 12,
    title: "Classic Collection",
    artist: "shohruhxon",
    artistId: 'shohruhxon',
    img: "/img/movie5.jpg",
    year: 2022,
    genre: 'Pop',
    language: 'uzbek',
    country: 'Uzbekistan',
    type: 'musicAlbom',
    songs: [
      {
        id: 1,
        title: "Melody",
        artist: "Artist C",
        audio: "/music/Official Arctic Monkeys - I Wanna Be Yours.mp3",
      },
    ],
  },
];
