/**
 * Visual Beats - video klip bo'limi uchun ma'lumotlar.
 * type: 'klip' - video kontent.
 */
export const visualBeatsData = [
  {
    id: 1001,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-1.avif',
    title: 'Die With A Smile',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '1110',
    dislike: '0',
  },
  {
    id: 1002,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-2.jpeg',
    title: 'The Amateur',
    year: 2024,
    genre: 'drama',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1003,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-3.jpg',
    title: 'Life',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1004,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-4.webp',
    title: 'Die With A Smile (Live)',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1005,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-5.jpg',
    title: 'The Amateur Trailer',
    year: 2024,
    genre: 'thriller',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/The Amateur _ Official Trailer.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1006,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Life - Premiere',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1007,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Life - Premiere',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1008,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Life - Premiere',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1009,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Life - Premiere',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1010,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-6.avif',
    title: 'Life - Premiere',
    year: 2020,
    genre: 'pop',
    language: 'russian',
    country: 'russia',
    type: 'klip',
    video: '/video/Zivert - Life   Премьера клипа.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1011,
    artistId: 'jah-khalib',
    img: '/img/movie-4.5-4.webp',
    title: 'Die With A Smile (Live)',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
  {
    id: 1012,
    artistId: 'shohruhxon',
    img: '/img/movie-4.5-4.webp',
    title: 'Die With A Smile (Live)',
    year: 2024,
    genre: 'pop',
    language: 'english',
    country: 'usa',
    type: 'klip',
    video: '/video/Lady_Gaga,_Bruno_Mars_Die_With_A_Smile_Official_Music_Video.mp4',
    like: '0',
    dislike: '0',
  },
];
